[package]
name = "omnibus-mobile"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["mobile"] }
dioxus-router.workspace = true
omnibus-shared = { path = "../shared" }
omnibus-frontend = { path = "../frontend", features = ["mobile"] }
reqwest.workspace = true
serde_json.workspace = true
